### ISSUE TITLE
Status report?

### ISSUE THREAD

**Issue by aemadrid** [artsy/gris#100]
It seems like an interesting project but doesn't seem to have momentum going. Are you using it internally in artsy? Are you still developing/maintaining the project?

**Comment by starsirius** [comment]
@aemadrid Yes, we are using it for a few projects internally at Artsy. While we don't super actively developing Gris currently, we will still maintain it to keep things in a good state and hope to see it evolve over time. That is, PRs are welcome!!

**Comment by aemadrid** [comment]
Thanks for the update! Was wondering because the routes rake task fails for newer versions of grape. I might send you a PR on that.
